name: Flutter Testing

on:
  push
  
jobs:
  test:
    runs-on: ghcr.io/cirruslabs/flutter:latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
